; Add wireframe pages here using the following format:
; path/to/create[title] = Plain text page title
; path/to/create[content] = Whatever text, setting filter below.

; Notes
; * Comments should be added on their own lines.
; * Currently, menu cache has to be cleared manually when visiting pages anonymously.
; * Currently, you have to refresh the page twice to pick up changes.

; Example
example/path[title]   = This is a awesome mockup
example/path[content] = <p>This is a really interesting wireframe with an embedded image:</p><div style="text-align:center"><img src="http://icanhascheezburger.files.wordpress.com/2007/01/i-can-has-cheezburger.jpg" /></div>